Task2-components1
katareena/movie pull request #2
Opened 2022-12-12 17:10 UTC by katareena

2022-12-19 16:34 UTC, MarharytaKrasikava requested changes

2022-12-26 19:49 UTC, MarharytaKrasikava requested changes

2022-12-26 19:49 UTC, MarharytaKrasikava commented on src/components/find-button/find-button.tsx
> +        <span>
what this span is for?

2022-12-26 19:49 UTC, MarharytaKrasikava commented on src/components/find-button/find-button.tsx
> +    <div className='find visually-hidden'>
What's the purpose of this component?

2022-12-26 19:49 UTC, MarharytaKrasikava commented on src/components/footer/footer.tsx
> +    <footer
Can `<footer>` include `div.footer-wrap` styles to get rid of the nested `<div>` that probably creates extra nesting?

2022-12-26 19:49 UTC, MarharytaKrasikava commented on src/components/genres/genres.tsx
> +            <Link to='#' className='genres__link'>
I think Genres buttons are not the links because they doesn't lead us to another page. They implement a filtering function.

2022-12-26 19:49 UTC, MarharytaKrasikava commented on src/components/sorting/sorting.tsx
> +          </ul>
This list has to be opened/closed on click.

2022-12-26 19:49 UTC, MarharytaKrasikava commented on src/components/sorting/sorting.tsx
> +        </div>
Can we get rid of extra nesting (`<div>`->`<ul>`) and leave only `<ul>`?

2022-12-27 12:49 UTC, MarharytaKrasikava commented on src/pages/main-page/main-page.tsx
> +        <Card />
Sorry, this is a wrong advice. It's correct to have `<Card>` it here

2022-12-29 13:10 UTC, katareena commented on src/components/edit/edit.tsx
> +        <button className='close'></button>
Yes, in general cases I try to do so. Thank you!
But this arrangement of the Close-button improves the user experience: when the user navigates through the interface using the keyboard, the Close-button should be the last in the queue of available fields.

2022-12-29 13:25 UTC, katareena commented on src/components/catalog/catalog.tsx
> +      <h2 className='visually-hidden'>Catalog</h2>
I read about it in the documentation: "..each <section> should be identified, typically by including a heading (<h1> - <h6> element) as a child of the <section> element, wherever possible...... Depending on the content, including a heading could also be good for YOU, so it is an option to consider." And also http://validator.w3.org/ issues a warning: https://prnt.sc/wnbQo8otVO0N

2022-12-29 13:35 UTC, katareena commented on src/components/header/header.tsx
> +        <h1 className='visually-hidden'>Movie</h1>
I read that this is a first-level header, which is not a meta tag, but together with the title and description meta tags are the basis for the presentation of the page for search engines. Having the right `<h1>`  is the most important condition for a good SEO promotion. Therefore, if there is no `<h1>` header in the design-layout, it is recommended to specify it and hide it

2022-12-29 13:40 UTC, katareena commented on src/pages/main-page/main-page.tsx
> +      </div>
where does it say that `<header>` cannot have wrappers? I couldn't find it/

2022-12-29 13:41 UTC, katareena commented on src/components/find-button/find-button.tsx
> +    <div className='find visually-hidden'>
it is specified in the design-layout: https://prnt.sc/K8da9PYlHG-D

2022-12-29 13:48 UTC, katareena commented on src/components/sorting/sorting.tsx
> +          </ul>
Yes it is implemented in the following PR

2022-12-29 14:01 UTC, katareena commented on src/components/genres/genres.tsx
> +            <Link to='#' className='genres__link'>
can it be as URL Search Param of react router, how it's done here: https://prnt.sc/rgELM_GgURoa
or is it a bad practice?

2022-12-29 14:23 UTC, MarharytaKrasikava commented on src/components/edit/edit.tsx
> +        <button className='close'></button>
Actually it's more correct to have keyboard navigation be respective to the visual order.

2022-12-29 14:33 UTC, MarharytaKrasikava commented on src/components/catalog/catalog.tsx
> +      <h2 className='visually-hidden'>Catalog</h2>
But there's no sense to have a hidden heading. So you can use <div> instead of <section> because you have only one section. But there's also a good option to make this paragraph a heading (I think it's more appropriate role for it):
![image](https://user-images.githubusercontent.com/47751829/209967928-c10fb630-312c-4315-a57b-905880d37735.png)

2022-12-29 14:45 UTC, MarharytaKrasikava commented on src/components/header/header.tsx
> +        <h1 className='visually-hidden'>Movie</h1>
Got your point) But you have NetflixRoulette as the name of the app... And "Find your movie" below is more appropriate heading. Also I don't think you should care about SEO promotion in this course at all :)

2022-12-29 14:50 UTC, MarharytaKrasikava commented on src/pages/main-page/main-page.tsx
> +      </div>
I wanted to emphasize that the search form also can be in the `<header>`

2022-12-29 14:53 UTC, MarharytaKrasikava commented on src/components/find-button/find-button.tsx
> +    <div className='find visually-hidden'>
it's not included in the homepage scope. It should be rendered in the Card component to get back to the search form.

2022-12-29 15:02 UTC, MarharytaKrasikava commented on src/components/genres/genres.tsx
> +            <Link to='#' className='genres__link'>
We don't know the context of your example doesn't contain filtering function. As in your functionality only content of the page changes and the module is only about handlers and hooks, use this instruments here.

2023-01-02 17:10 UTC, katareena commented on src/components/catalog-item/catalog-item.tsx
> +            <span>{released}</span>
updated

2023-01-02 17:26 UTC, katareena commented on src/components/edit/edit.tsx
> +        <button className='close'></button>
I agree, this is a drop-down menu and the first item in the visual order is a menu item.

2023-01-02 17:35 UTC, katareena commented on src/components/catalog/catalog.tsx
> +      <h2 className='visually-hidden'>Catalog</h2>
`.catalog__result-test` does not reflect the essence of the section, it is just an additional clarification to the title. If we assign this to the title, then navigation and understanding of the essence of the section for users of screen readers will be difficult

2023-01-02 17:53 UTC, katareena commented on src/components/notify-modal/notify-modal.scss
> +  padding-bottom: 45px;
updated

2023-01-02 17:53 UTC, katareena commented on src/components/header/header.tsx
> +        <h1 className='visually-hidden'>Movie</h1>
updated

2023-01-02 17:57 UTC, katareena commented on src/pages/main-page/main-page.tsx
> +      </div>
but there will be a change of the search block and the card block

2023-01-02 17:59 UTC, katareena commented on src/components/find-button/find-button.tsx
> +        <span>
updated

2023-01-02 18:03 UTC, katareena commented on src/components/find-button/find-button.tsx
> +    <div className='find visually-hidden'>
how is that? FindButton is located in the header-component scope and changes with AddButton

2023-01-02 18:11 UTC, katareena commented on src/components/genres/genres.tsx
> +            <Link to='#' className='genres__link'>
ok, let's leave it to the block with routing

2023-01-02 18:17 UTC, katareena commented on src/components/footer/footer.tsx
> +    <footer
updated

2023-01-02 18:29 UTC, merged