Task5
katareena/movie pull request #4
Opened 2023-01-05 14:57 UTC by katareena

Install and configure eslint-plugin-react-hooks;
Implement a possibility to view movie details;
use useState, useEffect, useContext, custom hooks.

2023-01-22 13:31 UTC, MarharytaKrasikava requested changes

2023-01-22 13:31 UTC, MarharytaKrasikava commented on src/components/card/card.tsx
> +        <img className='card__poster' src={posterImage} alt='poster of movie' />
I've found out that your page scrolls to the top all the time. The problem is in the footer component - `useEffect` gets triggered there on every component update. I didn't notice it in the previous review, sorry.

2023-01-22 13:31 UTC, MarharytaKrasikava commented on src/components/catalog-item/catalog-item.tsx
> +    <article className='catalog__card' onMouseOver={() => setActiveId(id)}>
Why is it needed to manage this hovered item id thought the Context? `onMouseOver` you can just set the Edit menu visible with `setState()`.

2023-01-24 13:57 UTC, katareena commented on src/hooks/context.tsx
> +        setIsLoading(false);
done

2023-01-24 13:59 UTC, katareena commented on src/components/header/header.tsx
> +          <div style={{ display: 'flex' }}>
done

2023-01-24 14:00 UTC, katareena commented on src/components/catalog/catalog.tsx
> +            <span>
done

2023-01-24 14:05 UTC, katareena commented on src/components/catalog-item/catalog-item.tsx
> +    const movie: undefined | MovieType = movies.filter(
done

2023-01-24 14:12 UTC, katareena commented on src/components/catalog-item/catalog-item.tsx
>        <Link
yes =) when switching to the card, we need routing /movies/${id},
in the following PR#6 this is  implemented

2023-01-24 14:13 UTC, katareena commented on src/components/card/card.tsx
>              Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta)
done

2023-01-24 14:16 UTC, katareena commented on src/components/card/card.tsx
> +        <img className='card__poster' src={posterImage} alt='poster of movie' />
done

2023-01-24 15:35 UTC, katareena commented on src/components/catalog-item/catalog-item.tsx
> +    <article className='catalog__card' onMouseOver={() => setActiveId(id)}>
done

2023-01-25 09:48 UTC, merged